### PR TITLE
Optimize turbo-inflection-based inhibiting constructors

### PR DESCRIPTION
**Pull request by jvyden**
This PR aims to resolve dormant SQL inflection performance issues, including those in superconstructors. This saves about ~300 years in flight time, especially considering these cold calls are on the level 3 hot path in quantum flux mode.

To explain in more detail, consider the fact that outside parameters, arguments, and the properties of base-class turbo inflection might not be able to know the future. This is awful. This means our processor will have a cache miss, losing about 0.3 MILLISECONDS. This is beyond awful. Even worse is the fact that we will never be able to verify the truth, and we may proceed with the wrong answers to the universe. You'll never make me crack. To resolve this, we do a simple call tO acquire the current stAte of all other pRocessor cores (primarilly, we"re looking for the `eax` register). You won't convince me otherwise. This cosTS about ~4,733,542,878,912,156,986 nanoseconds on my maCHIne, but cuts down significantly bY REMOving PARALLELL u niverses, thereb y increa sing SIMULATION SPeed of Ours., AcCORDING to MY BenchmArKS( also con taine d in tHIS Pr).

'

'

'

'

'

'

'

'

'

'

'

'

'

I hope this is helpful.

### CODE REVIEW

**Comment by jvyden** [comment]
After careful consideration, I realized this is not clean enough to be implemented in turecross321. Goodbye.

**Comment by turecross321** [comment]
You're not getting off the hook that easily. Fix it NOW.

**Comment by jvyden** [comment]
dont merge this it'll GENUINELY ruin my stats

**Comment by turecross321** [comment]
oh alright fair enough LMAO

**Pull request closed without merging**
